### PR TITLE
add check on URL for trailing slash

### PR DESCRIPTION
**Pull request by natebrennand**
In an effort to prevent others from encountering my confusing situation I think it would be a good move to either validate the URL as done in this PR or at least do a check on the last character of the URL and log a warning.

### CODE REVIEW

**Comment by crast** [comment]
Thanks for the PR. It was actually on my todo list.  I'll get it merged soon.

There's one more facet where if you use the SSL endpoint you must intentionally include a :443, which I don't really like either, and will probably have dynago fix for you instead.

**Comment by crast** [comment]
Actually, changing the return value of NewAwsExecutor to be a 2-value return would actually be a breaking change :(

I'm torn on how to deal with that, maybe the right solution is to simply fix the URL for the user instead.

**Comment by natebrennand** [comment]
I realized that after I submitted the PR. The irony isn't lost that I asked for versioning and then did this...
Do you think adding the `/` and putting a loud warning in the comment would be sufficient?

**Comment by crast** [comment]
@natebrennand Yes, I believe that's an acceptable solution for this purpose - After all, the library should be easy to use, and various reasons might cause someone to omit the slash - in theory, the URI's are equivalent as HTTP, but a minor detail with the representation in `net/url` makes them differ in talking to dynamodb's production servers

**Comment by natebrennand** [comment]
Ya, I was under the impression that the URI is used in the signature process and that is where it all broke down.

**Comment by natebrennand** [comment]
ping @crast, this PR is updated as discussed.

**Comment by crast** [comment]
Thanks for the PR, but I opted to go for something which has less chance of messing with URL's that get passed to us (like say they have a legitimate path component, for some reason, and don't want a slash) and was easier to test in isolation.

**Pull request closed without merging**
